name: null

channels:
  - defaults
  - conda-forge

dependencies:
  - python=3.9
  - numpy=1.21
  - matplotlib=3.7
  - pandas=1.5
  - scanpy=1.9
  - pip
  - pip:
    - ipywidgets
    - ipykernel
    - leidenalg
    - openai
    - python-dotenv
